/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 nodejs.gltf --transform 
Files: nodejs.gltf [583.21KB] > C:\Users\tingtinghu321\Desktop\3D\nodejs-transformed.glb [37.34KB] (94%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/nodejs-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["Material.044"]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={1.112}
      />
      <mesh
        geometry={nodes.Curve003.geometry}
        material={materials["Material.001"]}
        position={[0, -0.107, 0.153]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={7.08}
      />
    </group>
  );
}

useGLTF.preload("/nodejs-transformed.glb");
